name: publish EncineCarlos.DataAccess
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

env:
    PROJECT_PATH: EncineCarlos.DataAccess/EncineCarlos.DataAccess.csproj
    OUTPUT_PACKAGE: ${{ github.workspace }}/output
jobs:
  publish:
    name: build, pack and publish
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: Install dotnet
        uses: actions/setup-dotnet@v3.0.3
        with:
            dotnet-version: 6.x
      
      - name: Restore dependencies
        run: dotnet restore ${{env.PROJECT_PATH}}
      
      - name: Build proejct
        run: dotnet build ${{env.PROJECT_PATH}} --no-restore -c Release

      - name: Get Version
        id: version
        uses: battila7/get-version-action@v2
      
      - name: pack the proejct
        run: dotnet pack ${{ env.PROJECT_PATH }} --no-restore --no-build -c release -p:PackageVersion=${{ steps.version.outputs.version-without-v }} --include-symbols --output ${{ env.OUTPUT_PACKAGE }}
       
      - name: push package
        run: dotnet nuget ${{ env.OUTPUT_PACKAGE }}\*.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_KEY}} --skip-duplicate